config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root "pages#index"
  resources :artists
  resources :productions
  resources :albums
  resources :songs
  get "search" => "songs#search"
  get "update_number/:type/:id" => "songs#update_number"
  get "top" => "songs#top_song", as: :top
  get "right_ads" => "pages#right_ads", as: :right_ads
  get "download/:id" => "songs#download", as: :download
end

app/views/share/_album_detail.html.erb
<div class="row album-detail">
  <div class="col-sm-2">
    <%= image_tag @album.image.url, class: "img-responsive cover-img" %>
  </div>
  <div class="col-sm-8">
    <h4 class="media-heading"><%= @album.kh_name %></h4>
    <p><%= link_to @album.production.kh_name, @album.production %></p>
    <p><%= render "share/social_share" %></p>
  </div>
</div>

app/views/share/_artist_detail.html.erb
<div class="row album-detail">
  <div class="col-sm-2">
    <%= image_tag @artist.image.url, class: "img-responsive cover-img" %>
  </div>
  <div class="col-sm-8">
    <h4 class="media-heading"><%= @artist.kh_name %></h4>
    <p><%= render "share/social_share" %></p>
  </div>
</div>

app/views/share/_content_ads.html.erb
<div class="content-ads">
  <div class="ads">
    <iframe src="<%= right_ads_path %>" width="1100" height="1000" border="0" scrolling="no" frameborder="0"></iframe>
  </div>
</div>

app/views/share/_fb_comment_box.html.erb
<div class="fb-comment">
  <h4><%= t "labels.comment" %></h4>
  <div class="fb-comments" data-href="<%=  request.original_url %>" data-numposts="5" data-width="100%"></div>
</div>

app/views/share/_fb_like_box.html.erb
<div class="fb-page" data-href="https://www.facebook.com/Sing24h-477007265670967/" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"></div>

app/views/share/_meta_og.html.erb
<%
  if "albums" == controller.controller_name
    title = @album.kh_name if @album
    description = @album.production.kh_name if @album
    image = @album.image.url if @album
  elsif "artists" == controller.controller_name
    title = @artist.kh_name if @artist
    image = @artist.image.url if @artist
  elsif "songs" == controller.controller_name
    title = @song.kh_title if @song
    description = "#{@song.album.production.kh_name} #{@song.album.kh_name}, ច្រៀងដោយ: #{@song.get_artist_list}" if @song
    image = @song.image.url if @song
  end
%>
<meta property="og:title" content= "<%= title %>" />
<meta property="og:description" content= "<%= description %>" />
<meta property="og:image" content= "<%= image %>" />
<meta property="og:url" content= "<%= request.original_url %>" />

<!-- twitter card meta -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="<%= title %>">
<meta name="twitter:description" content="<%= description %>">
<meta name="twitter:image:src" content="<%= image %>">

app/views/share/_player.html.erb
<% if @songs.present? %>
  <div class="player">
    <div class="audio-player" data-total="<%= @songs.count %>">
      <div class="mask"></div>
      <div class="promotion-img"></div>
      <div class="audio-control">
        <p class="audio-title"></p>
        <p class="audio-artist"></p>
        <p class="audio-play-number"></p>
        <div class='glyphicon glyphicon-remove-circle btn-close'></div>
        <div class="glyphicon glyphicon-collapse-down btn-show-promotion"></div>
        <span class="btn-prev"></span>
        <span class="btn-next"></span>
        <span class="btn-repeat-song" title=""></span>
        <audio id="audio-player" src="<%= @songs.first.url if @songs.present? %>" type="audio/mp3"></audio>
      </div>
    </div>
    <div class="playlist">
      <table class="table table-hover table-songs">
        <tbody>
          <%= render @songs %>
        </tbody>
      </table>
    </div>
  </div>
  <%= render "share/content_ads" %>
  <h4><%= t "labels.lyric" %></h4>
  <div class="lyric"></div>

<% else %>
  <center>
    <hr>
    <h4><strong><%= t "labels.no_data" %></strong></h4>
  </center>
<% end %>

app/views/share/_right_ads1.html.erb
<div class="right-ads">
  <div class="ads">
    <iframe src="<%= right_ads_path %>" width="1100" height="1000" border="0" scrolling="no" frameborder="0"></iframe>
  </div>
</div>

app/views/share/_right_ads2.html.erb
<div class="right-ads2">
  <div class="ads">
    <iframe src="<%= right_ads_path %>" width="1100" height="1000" border="0" scrolling="no" frameborder="0"></iframe>
  </div>
</div>

app/views/share/_right_part.html.erb
<div class="col-md-3">
  <%= render "share/right_ads1" %>
</div>

app/views/share/_search.html.erb
 <div class="song-search">
   <%= search_form_for Song.ransack(params[:q]), class: "navbar-form navbar-left form-search"  do |f| %>
    <div class="input-group">
      <%= f.text_field :keyword_cont, placeholder: t("labels.search_placeholder"),
        class: "form-control search-bar", size: "50", autocomplete: "off" %>
      <span class="input-group-btn">
        <%= button_tag type: "submit", class: "btn btn-default btn-search" do %>
          <span class="glyphicon glyphicon-search"></span>
        <% end %>
      </span>
    </div>
  <% end %>
  <div class="autocomplete-search-results"></div>
</div>

app/views/share/_search_result.html.erb
<div class="row search-result">
  <div class="col-sm-3 col-md-2 song-image">
    <%= link_to song do %>
      <%= image_tag song.image.url, class: "img-responsive" %>
    <% end %>
  </div>

  <div class="col-sm-8 col-md-8 song-result">
    <h4 class="title"><%= link_to song.kh_title, song %></h4>
    <p class="album"><%= link_to song.album.kh_name, song.album %> | <%= get_artist_with_link(song).html_safe %></p>
    <p class="play-number">
      <span class="glyphicon glyphicon-headphones"></span> <%= number_with_precision song.play_number, precision: 0, delimiter: "," %>
    </p>
    <p><span class="fb-like" data-href="<%= song_url(song.id) %>" data-width="100%" data-layout="  button_count" data-action="like" data-show-faces="false" data-share="true"></span></p>
  </div>
</div>

<!-- only for load fb-sdk -->
<div class="player"></div>

app/views/share/_social_share.html.erb
<div class="fb-action">
  <span class="fb-like" data-href="<%=  request.original_url %>" data-width="100%" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></span>
  <span>
    <a href="https://twitter.com/share" class="twitter-share-button"{count} data-via="angkorvoice"></a>
  </span>
  <span>
    <script src="https://apis.google.com/js/plusone.js"></script>
    <g:plus action="share" annotation="bubble"></g:plus>
  </span>
</div>

app/views/share/_song_detail.html.erb
<div class="row album-detail">
  <div class="col-sm-2">
    <%= image_tag @song.image.url, class: "img-responsive cover-img" %>
  </div>
  <div class="col-sm-8">
    <h4 class="media-heading"><%= @song.kh_title %></h4>
    <p><%= link_to @song.album.kh_name, @song.album %></p>
    <p><%= get_artist_with_link(@song).html_safe %></p>
    <p><%= render "share/social_share" %></p>
  </div>
</div>