config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root "pages#index"
  resources :artists
  resources :productions
  resources :albums
  resources :songs
  get "search" => "songs#search"
  get "update_number/:type/:id" => "songs#update_number"
  get "top" => "songs#top_song", as: :top
  get "right_ads" => "pages#right_ads", as: :right_ads
  get "download/:id" => "songs#download", as: :download
end

app/models/song.rb
class Song < ActiveRecord::Base
  include RailsAdminSong
  paginates_per Settings.pagination.per_page

  mount_uploader :image, CoverImageUploader
  mount_uploader :bg_image, BannerImageUploader

  belongs_to :album
  belongs_to :country
  belongs_to :promotion_image
  belongs_to :user

  has_many :song_artists, dependent: :destroy
  has_many :artists, through: :song_artists

  has_many :song_types, dependent: :destroy
  has_many :types, through: :song_types

  validates :artists, presence: true
  validates :album, presence: true
  validates :country, presence: true
  validates :en_title, presence: true
  validates :kh_title, presence: true
  validates :types, presence: true
  validates :url, presence: true
  validates :image, presence: true

  scope :find_song, ->term{where("keyword LIKE ?", "%#{term}%").limit 5}
  scope :find_all_except, ->id, limit{where.not(id: id).limit(limit)}
  scope :top_song, ->limit{order(play_number: :DESC).limit(limit)}

  before_save :set_keyword

  def name
    kh_title
  end

  def get_artist_list
    artists.map{|artist| "#{artist.kh_name}"}.join(", ")
  end

  def update_play_number
    update_attribute :play_number, self.play_number + 1
  end

  def update_download_number
    update_attribute :download_number, self.download_number + 1
  end

  private
  def get_artists
    artists.map{|artist| "#{artist.en_name} #{artist.kh_name}"}.join(" ")
  end

  def get_types
    types.map{|type| "#{type.en_type} #{type.kh_type}"}.join(" ")
  end

  def set_keyword
    self.keyword = "#{album.production.kh_name} #{album.production.en_name}
      #{kh_title} #{en_title} #{album.kh_name} #{album.en_name} #{country.kh_name}
      #{country.en_name} #{get_artists} #{get_types}"
  end
end

app/models/song_type.rb
class SongType < ActiveRecord::Base
  belongs_to :song
  belongs_to :type
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @result = Song.ransack(params[:q]).result.page(params[:page])
  end

  def show
    @songs = Song.where(id: params[:id])
    @song = Song.find params[:id]
    @album = @song.album
    @similar_songs = @album.songs.find_all_except @song.id, 5
  end

  def search
    respond_to do |format|
      format.html
      format.json {@songs = Song.find_song params[:term]}
    end
  end

  def top_song
    @result = Song.top_song 20
    render :top
  end

  def update_number
    song = Song.find params[:id]
    if("play" == params[:type])
      song.update_play_number
    else
      song.update_download_number
    end
    render nothing: true
  end

  def download
    require "open-uri"
    song = Song.find params[:id]
    data = open(song.url).read
    send_data data, disposition: "attachment", filename: "#{song.kh_title}.mp3"
  end
end

app/views/songs/_other_song.html.erb
<div class="media album-detail">
  <div class="media-left">
    <%= link_to song do %>
      <%= image_tag song.image.url, width: "90", class: "album-image" %>
    <% end %>
  </div>
  <div class="media-body">
    <h5 class="media-heading"><%= link_to song.kh_title, song %></h5>
    <p><%= link_to song.album.kh_name, song.album %></p>
    <p><%= get_artist_with_link(song).html_safe %></p>
  </div>
</div>

app/views/songs/_song.html.erb
<tr id="song-<%= song_counter %>" class="row-song"
  data-id="<%= song.id %>"
  data-khtitle="<%= song.kh_title %>"
  data-artist="<%= get_artist_with_link song %>"
  data-url="<%= song.url %>"
  data-lyric="<%= song.lyric %>"
  data-promotion-link="<%= song.promotion_image.link if song.promotion_image %>"
  data-bg-image="<%= song.bg_image.url %>"
  data-promotion-image="<%= song.promotion_image.image.url if song.promotion_image %>"
  data-play-number="<%= song.play_number %>">
  <td width="50%" class="title"><%= "#{song_counter + 1}. #{song.kh_title}" %></td>
  <td width="30%" class="artist"><%= get_artist_with_link(song).html_safe %></td>
  <td width="10%">
    <span class="fb-share-button" data-href="<%= song_url(song.id) %>" data-layout="button_count"></span>
  </td>
  <td width="5%"><%= link_to "", song_path(song), class: "glyphicon glyphicon-headphones", title: t("labels.listen") if @songs.count > 1 %></td>
  <td width="5%"><%= link_to "", download_path(song.id), class: "glyphicon glyphicon-save btn-download", title: t("labels.download"), target: "_blank" %></td>
</tr>

app/views/songs/index.html.erb
<%= provide :title, t("labels.search") %>
<div class="row">
  <div class="col-md-9">
    <%= render "share/content_ads" %>
    <hr>
    <%= render partial: "share/search_result", collection: @result, as: :song %>
    <div class="paginate">
      <%= paginate_page @result %>
    </div>
  </div>
  <%= render "share/right_part" %>
</div>

app/views/songs/index.js.erb
<% if @songs.count > 0 %>
  $(".song-auto-result").show();
  $(".auto-song").html("<%= j render partial: 'share/song_autocomplete', collection: @songs %>");
<% else %>
  $(".song-auto-result").hide();
<% end %>

<% if @artists.count > 0 %>
  $(".artist-auto-result").show();
  $(".auto-artist").html("<%= j render partial: 'share/artist_autocomplete', collection: @artists %>");
<% else %>
  $(".artist-auto-result").hide();
<% end %>

<% if @albums.count > 0 %>
  $(".album-auto-result").show();
  $(".auto-album").html("<%= j render partial: 'share/album_autocomplete', collection: @albums %>");
<% else %>
  $(".album-auto-result").hide();
<% end %>

app/views/songs/show.html.erb
<%= provide :title, @song.kh_title %>
<div class="row">
  <div class="col-md-9 album">
    <%= render "share/song_detail" %>
    <%= render "share/player" %>
    <%= render "share/fb_comment_box" %>
  </div>
  <div class="col-md-3">
    <%= render "share/fb_like_box" %>
    <%= render "share/right_ads2" %>
    <h4>
      <%= link_to @song.album do %>
        <%= t "labels.other_songs" %>
        <span class="glyphicon glyphicon-menu-right icon-more-2"></span>
      <% end %>
    </h4>
    <%= render partial: "other_song", collection: @similar_songs, as: :song %>
  </div>
</div>

app/views/songs/top.html.erb
<%= provide :title, t("labels.top") %>
<div class="row">
  <div class="col-md-9">
    <%= render "share/content_ads" %>
    <hr>
    <%= render partial: "share/search_result", collection: @result, as: :song %>
  </div>
  <%= render "share/right_part" %>
</div>