config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root "pages#index"
  resources :artists
  resources :productions
  resources :albums
  resources :songs
  get "search" => "songs#search"
  get "update_number/:type/:id" => "songs#update_number"
  get "top" => "songs#top_song", as: :top
  get "right_ads" => "pages#right_ads", as: :right_ads
  get "download/:id" => "songs#download", as: :download
end

app/views/layouts/_footer.html.erb
<p>Sing24h.com. Copy right &copy; 2016</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo2.png", width: "56", class: "img-responsive logo" %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render "share/search" %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("menus.home"), root_path %></li>
        <li><%= link_to t("menus.top"), top_path %></li>
        <li><%= link_to t("menus.productions"), productions_path %></li>
        <li><%= link_to t("menus.artists"), artists_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_meta.html.erb
<meta name="title" content="Best Online Music Website in Cambodia | Sing24h.com">
<meta name="description" content="Listen new and hot songs, download hot songs, search hot and latest songs with high quality | Sing24h.com">
<meta name="keywords" content="sing24h, song, music, mp3, download song, search song, song with high quality, online music, online songs, play latest songs, best online music website in Cambodia">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "logo.png" %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="google-site-verification" content="uR2ja9Eis_5FTtGWpebsd-5QooehDDrJrJ9-5hsxaXY" />
  <link href='http://fonts.googleapis.com/css?family=Hanuman' rel='stylesheet' type='text/css'>
  <%= render "layouts/shim" %>
  <%= render "layouts/meta" %>
  <%= render "share/meta_og" %>
</head>
<body data-no-turbolink="true">

  <!-- facebook comment -->
    <div id="fb-root"></div>
  <!-- end -->

  <div class="header">
    <%= render "layouts/header" %>
  </div>
  <div class="container-fluid content">
    <%= yield %>
  </div>
  <div class="container-fluid footer">
    <%= render "layouts/footer" %>
  </div>
</body>
</html>

app/views/layouts/application_v2.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield(:title) %></title>
  <%= stylesheet_link_tag    'application_2', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application_2', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Hanuman' rel='stylesheet' type='text/css'>
  <%= render "layouts/shim" %>
</head>
<body style="padding-top: 0px;">
  <div class="container-fluid content">
    <%= yield %>
  </div>
</body>
</html>